# Lab 02: Manipulate PyTorch Tensors -- exercise

In [ ]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [4]:
ts_a = torch.tensor([[1,2],[3,4]])
ts_b = torch.tensor([[10,20], [30, 40]])
ts_c = ts_a + ts_b

print(ts_c)

tensor([[11, 22],
        [33, 44]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [5]:
print(ts_a.dim(), ts_a.size(), ts_a.type())

2 torch.Size([2, 2]) torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [7]:
ts_a = ts_a.long()
print(ts_a.type())

torch.LongTensor
torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [11]:
ts_rand = torch.rand(5,2,3)
print(ts_rand)
print(ts_rand.type())
print(ts_rand.dim())
print(ts_rand.size())
print(ts_rand.size(1))

tensor([[[0.9483, 0.6608, 0.1490],
         [0.8335, 0.9077, 0.9171]],

        [[0.5687, 0.9424, 0.5146],
         [0.6169, 0.4229, 0.8106]],

        [[0.6134, 0.4329, 0.6599],
         [0.2139, 0.6518, 0.1960]],

        [[0.5801, 0.1659, 0.2214],
         [0.4603, 0.5914, 0.1681]],

        [[0.7059, 0.1246, 0.7297],
         [0.5981, 0.0275, 0.0778]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [13]:
ts_zeros = torch.zeros(2,3,4,5)
print(ts_zeros)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
